// Generated by egui-themer (https://github.com/grantshandy/egui-themer).

use eframe::egui::{self, CornerRadius};

use egui::{
    Color32, Margin, Stroke, Style, Vec2, Visuals,
    epaint::Shadow,
    style::{
        Interaction, ScrollStyle, Selection, Spacing, TextCursorStyle, WidgetVisuals, Widgets,
    },
};

pub const TEXT_HEADER_SIZE: f32 = 18.0;
pub const TEXT_SUBHEADER_SIZE: f32 = 15.0;
pub const TEXT_BODY_SIZE: f32 = 12.0;

pub fn style() -> Style {
    Style {
        // override the text styles here:
        // override_text_style: Option<TextStyle>

        // override the font id here:
        // override_font_id: Option<FontId>

        // set your text styles here:
        // text_styles: BTreeMap<TextStyle, FontId>,

        // set your drag value text style:
        // drag_value_text_style: TextStyle,
        spacing: Spacing {
            item_spacing: Vec2 { x: 8.0, y: 6.0 },
            window_margin: Margin {
                left: 6,
                right: 6,
                top: 6,
                bottom: 6,
            },
            button_padding: Vec2 { x: 4.0, y: 1.0 },
            menu_margin: Margin {
                left: 6,
                right: 6,
                top: 6,
                bottom: 6,
            },
            indent: 18.0,
            interact_size: Vec2 { x: 40.0, y: 18.0 },
            slider_width: 100.0,
            combo_width: 100.0,
            text_edit_width: 280.0,
            icon_width: 14.0,
            icon_width_inner: 8.0,
            icon_spacing: 4.0,
            tooltip_width: 500.0,
            indent_ends_with_horizontal_line: false,
            combo_height: 200.0,
            scroll: ScrollStyle {
                bar_width: 10.0,
                handle_min_length: 12.0,
                bar_inner_margin: 4.0,
                bar_outer_margin: 0.0,
                ..Default::default()
            },
            ..Default::default()
        },
        interaction: Interaction {
            resize_grab_radius_side: 5.0,
            resize_grab_radius_corner: 10.0,
            show_tooltips_only_when_still: true,
            ..Default::default()
        },
        visuals: Visuals {
            dark_mode: true,
            override_text_color: None,
            widgets: Widgets {
                noninteractive: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(108, 112, 134, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(205, 214, 244, 255),
                    },
                    expansion: 0.0,
                },
                inactive: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    bg_stroke: Stroke {
                        width: 0.0,
                        color: Color32::from_rgba_premultiplied(0, 0, 0, 0),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(205, 214, 244, 255),
                    },
                    expansion: 0.0,
                },
                hovered: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(127, 132, 156, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 3,
                        ne: 3,
                        sw: 3,
                        se: 3,
                    },
                    fg_stroke: Stroke {
                        width: 1.5,
                        color: Color32::from_rgba_premultiplied(205, 214, 244, 255),
                    },
                    expansion: 1.0,
                },
                active: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(30, 30, 46, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(30, 30, 46, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(127, 132, 156, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 2.0,
                        color: Color32::from_rgba_premultiplied(205, 214, 244, 255),
                    },
                    expansion: 1.0,
                },
                open: WidgetVisuals {
                    bg_fill: Color32::from_rgba_premultiplied(30, 30, 46, 255),
                    weak_bg_fill: Color32::from_rgba_premultiplied(49, 50, 68, 255),
                    bg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(24, 24, 37, 255),
                    },
                    corner_radius: CornerRadius {
                        nw: 2,
                        ne: 2,
                        sw: 2,
                        se: 2,
                    },
                    fg_stroke: Stroke {
                        width: 1.0,
                        color: Color32::from_rgba_premultiplied(210, 210, 210, 255),
                    },
                    expansion: 0.0,
                },
            },
            selection: Selection {
                bg_fill: Color32::from_rgba_premultiplied(0, 92, 128, 255),
                stroke: Stroke {
                    width: 1.0,
                    color: Color32::from_rgba_premultiplied(192, 222, 255, 255),
                },
            },
            hyperlink_color: Color32::from_rgba_premultiplied(90, 170, 255, 255),
            faint_bg_color: Color32::from_rgba_premultiplied(5, 5, 5, 0),
            extreme_bg_color: Color32::from_rgba_premultiplied(17, 17, 27, 255),
            code_bg_color: Color32::from_rgba_premultiplied(64, 64, 64, 255),
            warn_fg_color: Color32::from_rgba_premultiplied(255, 143, 0, 255),
            error_fg_color: Color32::from_rgba_premultiplied(255, 0, 0, 255),
            window_corner_radius: CornerRadius {
                nw: 6,
                ne: 6,
                sw: 6,
                se: 6,
            },
            window_shadow: Shadow {
                spread: 0,
                color: Color32::from_rgba_premultiplied(0, 0, 0, 96),
                blur: 15,
                offset: [10, 20],
            },
            window_fill: Color32::from_rgba_premultiplied(24, 24, 37, 255),
            window_stroke: Stroke {
                width: 1.0,
                color: Color32::from_rgba_premultiplied(49, 50, 68, 255),
            },
            menu_corner_radius: CornerRadius {
                nw: 6,
                ne: 6,
                sw: 6,
                se: 6,
            },
            panel_fill: Color32::from_rgba_premultiplied(24, 24, 37, 255),
            popup_shadow: Shadow {
                spread: 0,
                color: Color32::from_rgba_premultiplied(0, 0, 0, 96),
                blur: 8,
                offset: [6, 10],
            },
            resize_corner_size: 12.0,
            text_cursor: TextCursorStyle {
                stroke: Stroke {
                    width: 2.0,
                    color: Color32::from_rgba_premultiplied(192, 222, 255, 255),
                },
                preview: false,
                ..Default::default()
            },
            clip_rect_margin: 3.0,
            button_frame: true,
            collapsing_header_frame: false,
            indent_has_left_vline: true,
            striped: false,
            slider_trailing_fill: false,
            ..Default::default()
        },
        animation_time: 0.08,
        explanation_tooltips: false,
        ..Default::default()
    }
}
