[package]
name = "rrise-headers"
version = "0.2.2"
edition = "2021"
authors = ["David Taralla <davidtaralla@gmail.com> & Contributors to the Rrise project"]
description = "A helper for Rrise, generating headers based on soundbank definition files"
repository = "https://github.com/dtaralla/rrise"
documentation = "https://docs.rs/rrise-headers"
readme = "README.md"
keywords = ["library", "sound", "3D", "wwise"]
categories = ["multimedia", "game-development"]
license-file = "LICENSE"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[build-dependencies]
walkdir = "2.3"
regex = { version = "1.7" }
lazy_static = "1.4"