[package]
name = "azilis-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = "0.14"
anyhow = "1"
modular-bitfield = "0.12"
rayon = "1"
profiling = "1"

[features]
profiler = ["profiling/profile-with-tracy"]
